# Generated by Django 5.1.1 on 2024-10-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0010_plato_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='categoria',
            field=models.CharField(blank=True, choices=[('desayuno', 'Desayuno'), ('postre', 'Postre'), ('te', 'Te')], max_length=10, null=True),
        ),
    ]
