# Generated by Django 5.1.2 on 2024-11-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0012_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
