# Generated by Django 5.1.2 on 2024-11-10 03:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0014_detallefactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
