# Generated by Django 5.1.2 on 2024-11-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0015_factura_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
    ]
