# Generated by Django 5.1.2 on 2024-11-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0016_plato_oculto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_especiales', models.ManyToManyField(blank=True, related_name='ofertas', to='comercio.diaespecial')),
                ('platos', models.ManyToManyField(related_name='ofertas', to='comercio.plato')),
            ],
        ),
    ]
